# Generated by Django 4.1 on 2022-08-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_news_options_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('variant', models.ManyToManyField(to='main.news')),
            ],
        ),
    ]
