# Generated by Django 4.1 on 2022-08-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(to='main.category'),
        ),
    ]
